### ISSUE TITLE
Can use hardware encoding node error

### ISSUE THREAD

**Issue by Kaos1337** [revenz/FileFlows#115]
Hello,
after the update to the version 0.8.1 today I'm having this error:

```
ERRR -> Execution error: Unable to cast object of type 'FileFlows.VideoNodes.CanUseHardwareEncoding' to type 'FileFlows.Plugin.Node'.
   at FileFlows.FlowRunner.Runner.LoadNode(FlowPart part) in /src/FlowRunner/Runner.cs:line 625
   at FileFlows.FlowRunner.Runner.ExecuteFlow(Flow flow, IPluginService pluginLoader, List`1 runFlows, Boolean failure) in /src/FlowRunner/Runner.cs:line 368
```

**Comment by revenz** [comment]
fixed in 0.8.1.285 nodes
