### ISSUE TITLE
External Database - All pooled connections are in use.

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#174]
FileFlows has cashed twice in six hours. Only recent change is allowing more worker node workers; up from 4 to 6.

```
2022-07-07 21:44:45.783 [ERRR] -> ExceptionMiddleware: One or more errors occurred. (Connect Timeout expired. All pooled connections are in use.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
   at FileFlows.Server.Controllers.WorkerController.UpdateWork(FlowExecutorInfo info) in /src/Server/Controllers/WorkerController.cs:line 157
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```
   
   `2022-07-08 05:20:32.085 [INFO] -> Making request[GET]: http://localhost:5000/api/node/by-address/INTERNAL_NODE
2022-07-08 05:20:36.134 [ERRR] -> Error in queue: One or more errors occurred. (Connect Timeout expired. All pooled connections are in use.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem() in /src/Server/Workers/WatchedLibrary.cs:line 238
2022-07-08 05:20:37.648 [INFO] -> Triggering worker: FlowRunnerMonitor
2022-07-08 05:20:45.163 [ERRR] -> Error in queue: One or more errors occurred. (Connect Timeout expired.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem() in /src/Server/Workers/WatchedLibrary.cs:line 238`

**Comment by revenz** [comment]
now using semaphore with limit of 10 to limit connections to the database
