### ISSUE TITLE
RaspberryPI: Run FileFlows Server

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#224]
update the server zip so it runs on a PI.  currently this error is shown
```
2022-07-20 12:50:48.995 [ERRR] -> Error: One or more errors occurred. (Unable to load shared library 'SQLite.Interop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSQLite.Interop.dll: cannot open shared object file: No such file or directory)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 201
   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 107
Error -> Error: One or more errors occurred. (Unable to load shared library 'SQLite.Interop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSQLite.Interop.dll: cannot open shared object file: No such file or directory)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 201
   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 107
```

**Comment by revenz** [comment]
Now detects if running on an ARM based CPU, and if so will use Microsoft.Data.SQLite instead of System.Data.SQLite.
