### ISSUE TITLE
[Bug] Plugins and Scripts go missing after repeated restarts of FF and Database

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#239]
1) Everything was working fine in the morning

2 ) Have been making changes to system outside of FileFlows; Fileflows and Database were not touched; System has restarted a dozen times

3) Starting up FileFlows, all Plugins and all custom Scripts were missing

[FileFlowsDB-Jul22-05.log](https://github.com/revenz/FileFlows/files/9165045/FileFlowsDB-Jul22-05.log)
[FileFlows-Jul22-08.log](https://github.com/revenz/FileFlows/files/9165046/FileFlows-Jul22-08.log)
[FileFlows-Jul22-09.log](https://github.com/revenz/FileFlows/files/9165047/FileFlows-Jul22-09.log)
[FileFlowsDB-Jul22-04.log](https://github.com/revenz/FileFlows/files/9165048/FileFlowsDB-Jul22-04.log)

Wondering if there is some odd race condition to do with FF coming up before database causing FF to not load the files or to potentially delete them?

**Comment by Sprooty** [comment]
This issue has occurred again, this time no restarts involved. Came back to notice all remaining files had failed with "flow not found"; restarting FF and Mara DB has restored my flows; but again, my FF scripts have gone missing. 

First hint of any issue in the logs appears to be
```

022-07-23 05:12:29.072 [INFO] -> Triggering worker: FlowRunnerMonitor
2022-07-23 05:12:29.234 [INFO] -> Triggering worker: FlowWorker
2022-07-23 05:12:29.287 [DBUG] -> Node 'Internal Processing Node' is not enabled
2022-07-23 05:12:29.398 [DBUG] -> Getting directory size (TEMP DIR) '/temp': 91.09 MB
2022-07-23 05:12:29.399 [DBUG] -> Getting node '62ebdb4d-cb78-4092-834b-ae5de79b5828' size (TEMP DIR) 'C:\Users\Sprooty\AppData\Roaming\FileFlows\Temp': 123.78 MB
2022-07-23 05:12:29.399 [DBUG] -> Getting node '98869b35-11fa-4823-a54f-57ea020bd7c5' size (TEMP DIR) 'C:\Users\user\AppData\Roaming\FileFlows\Temp': 92.83 MB
2022-07-23 05:12:29.789 [INFO] -> Making request [GET]: https://fileflows.com/api/plugin?rand=133030267497890811
2022-07-23 05:12:30.709 [ERRR] -> ExceptionMiddleware: Could not find a part of the path '/app/Data/Scripts/System'.REQUEST [GET] [200]: /api/flow/65e4f630-ad39-4b37-8fba-285d28f67c3d
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at FileFlows.Server.Controllers.ScriptController.GetAll(String directory, Boolean system) in /src/Server/Controllers/ScriptController.cs:line 64
   at FileFlows.Server.Controllers.ScriptController.GetAll() in /src/Server/Controllers/ScriptController.cs:line 25
   at FileFlows.Server.Controllers.FlowController.GetElements(FlowType type) in /src/Server/Controllers/FlowController.cs:line 433
   at FileFlows.Server.Controllers.FlowController.Get(Guid uid) in /src/Server/Controllers/FlowController.cs:line 334
   at lambda_method267(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at FileFlows.Server.Middleware.LoggingMiddleware.Invoke(HttpContext context) in /src/Server/Middleware/LoggingMiddleware.cs:line 53
   at FileFlows.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in /src/Server/Middleware/ExceptionMiddleware.cs:line 40
2022-07-23 05:12:30.731 [INFO] -> Setting library file status to: FlowNotFound - /tv1/Gold Rush- White 
```

all remaining files appear to fail with this error.

**Comment by revenz** [comment]
is this still happening on v1.0.0?

**Comment by Sprooty** [comment]
Not sure ill get around to a situation where this may be reproduced. Will close off.
