### ISSUE TITLE
Error and odd behavior when performing a folder input flow

### ISSUE THREAD

**Issue by liquidate** [revenz/FileFlows#27]
1. Create a library, enable the "Folders" toggle (we need to monitor folders, not files)
2. Download and rename the folders.json.txt to folders.json
3. Import the flow
4. Correct the zip export folder location as required
5. Add a folder with one or more files into the library folder

Result: Error when setting the original file.  In addition, when processing occurs there are times when both the parent folder and some of the nested files/folders appear as individual process items (I expect only a single item to be processed when a single folder is found, not the folder and some of it's children).

2022-04-03 15:07:05.0540 - INFO -> ======================================================================
2022-04-03 15:07:05.0551 - INFO -> Executing Node 1: Input Folder
2022-04-03 15:07:05.0561 - INFO -> ======================================================================
2022-04-03 15:07:05.0610 - INFO -> ======================================================================
2022-04-03 15:07:05.0616 - INFO -> Executing Node 2: Zip
2022-04-03 15:07:05.0622 - INFO -> ======================================================================
2022-04-03 15:07:05.0721 - INFO -> Compressing '/media/seedbox/Test Folder' to '/media/zipped/Test Folder.zip'
2022-04-03 15:07:05.0761 - INFO -> NOT changing owner on working file: /media/zipped/Test Folder.zip, temp path: /temp/Runner-eb850601-c81f-4125-ab30-b50c02d1b94c
2022-04-03 15:07:05.0768 - INFO -> Zip created at: /media/zipped/Test Folder.zip
2022-04-03 15:07:05.0791 - INFO -> ======================================================================
2022-04-03 15:07:05.0798 - INFO -> Executing Node 3: Original File
2022-04-03 15:07:05.0803 - INFO -> ======================================================================
2022-04-03 15:07:05.0811 - INFO -> NOT changing owner on working file: /media/seedbox/Test Folder, temp path: /temp/Runner-eb850601-c81f-4125-ab30-b50c02d1b94c
**2022-04-03 15:07:05.0909 - ERRR -> Execution error: Could not find file '/media/seedbox/Test Folder'.
   at System.IO.FileInfo.get_Length()
   at FileFlows.Plugin.NodeParameters.SetWorkingFile(String filename, Boolean dontDelete) in C:\BuildAgent\work\FileFlows\Plugin\NodeParameters.cs:line 211
   at FileFlows.BasicNodes.File.OriginalFile.Execute(NodeParameters args) in C:\BuildAgent\work\FileFlowsPlugins\BasicNodes\File\OriginalFile.cs:line 16
   at FileFlows.FlowRunner.Runner.RunActual(IFlowRunnerCommunicator communicator) in C:\BuildAgent\work\FileFlows\FlowRunner\Runner.cs:line 325**
2022-04-03 15:07:05.1021 - INFO -> Original Size: 0
2022-04-03 15:07:05.1026 - INFO -> Final Size: 0
2022-04-03 15:07:05.1036 - INFO -> Output Path: /media/zipped/Test Folder.zip
2022-04-03 15:07:05.1046 - INFO -> Making request[POST]: http://localhost:5000/api/worker/work/finish
2022-04-03 15:07:05.1126 - INFO -> Connection_Closed

[Zip Folders.json.txt](https://github.com/revenz/FileFlows/files/8405615/Zip.Folders.json.txt)

**Comment by revenz** [comment]
Fixed in next version.  Also the email body has to use the scriban format so the variables are 

```
Zipping the following folder :

{{folder.Name}}.zip
```
i.e. double {{ }} instead of single.
