### ISSUE TITLE
Exception thrown when files are created, modified, or deleted on a library with Folder Watch enabled

### ISSUE THREAD

**Issue by liquidate** [revenz/FileFlows#29]
When adding, renaming, then deleting a file, added to the root of a folder watch library, I receive the following exceptions: 

```
2022-04-06 21:49:48.8784 - DBUG -> Scan started on 'Seedbox': /media/seedbox
2022-04-06 21:49:48.8790 - DBUG -> Files queued for 'Seedbox': 1 / 1
2022-04-06 21:50:17.7371 - ERRR -> Error in queue: Could not find file '/media/seedbox/New Text Document.txt'.
   at System.IO.FileSystemInfo.ThrowNotFound(String path)
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at FileFlows.Server.Workers.WatchedLibrary.FileIsHidden(String fullpath) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 204
   at FileFlows.Server.Workers.WatchedLibrary.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 57
2022-04-06 21:50:37.7396 - INFO -> Error reading folder '/media/seedbox/test.txt' cannot add to library yet, will try again: Not a directory : '/media/seedbox/test.txt'
...
2022-04-06 21:50:51.7443 - INFO -> Error reading folder '/media/seedbox/test.txt' cannot add to library yet, will try again: Not a directory : '/media/seedbox/test.txt'
2022-04-06 21:50:53.7449 - ERRR -> Error in queue: Could not find file '/media/seedbox/test.txt'.
   at System.IO.FileSystemInfo.ThrowNotFound(String path)
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at FileFlows.Server.Workers.WatchedLibrary.FileIsHidden(String fullpath) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 204
   at FileFlows.Server.Workers.WatchedLibrary.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 57
2022-04-06 21:50:57.7456 - ERRR -> Error in queue: Could not find file '/media/seedbox/test.txt'.
   at System.IO.FileSystemInfo.ThrowNotFound(String path)
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at FileFlows.Server.Workers.WatchedLibrary.FileIsHidden(String fullpath) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 204
   at FileFlows.Server.Workers.WatchedLibrary.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 57
2022-04-06 21:50:58.8785 - DBUG -> Scan started on 'Seedbox': /media/seedbox
2022-04-06 21:50:58.8790 - DBUG -> Files queued for 'Seedbox': 1 / 1
```

this actually crops up while using Syncthing to synchronize folders from remote servers.  Syncthing will create a folder, then it apparently makes .tmp files as it syncs the contents down.  Those .tmp are converted into files, and FileFlows seems to get confused and considers them missing:

```
2022-04-06 21:41:57.5974 - DBUG -> New unknown folder: /media/seedbox/TEST_FOLDER
2022-04-06 21:41:57.6160 - DBUG -> Time taken "00:00:00.0194581" to successfully add new library file: "/media/seedbox/TEST_FOLDER"
2022-04-06 21:41:58.6343 - ERRR -> Error in queue: Could not find file '/media/seedbox/TEST_FOLDER/.syncthing.Videos.url.tmp'.
   at System.IO.FileSystemInfo.ThrowNotFound(String path)
   at System.IO.FileSystem.GetAttributes(String fullPath)
   at FileFlows.Server.Workers.WatchedLibrary.FileIsHidden(String fullpath) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 204
   at FileFlows.Server.Workers.WatchedLibrary.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\BuildAgent\work\FileFlows\Server\Workers\WatchedLibrary.cs:line 57
2022-04-06 21:41:58.8954 - INFO -> Executing: /root/.dotnet/dotnet "FileFlows.FlowRunner.dll" "--uid" "8928f344-37cb-471a-a6f6-fdca3dc4b3e1" "--libfile" "c9e8e022-0974-47d9-8d62-486c0bfb095e" "--tempPath" "/temp" "--baseUrl" "http://localhost:5000/" "--server"
```

**Comment by revenz** [comment]
added a file/folder exists check after an item is dequeued.
