### ISSUE TITLE
Execution error: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#314]
Version: 1.0.3.1963

I have a flow that runs a custom script for MkvMerge. I also have a node running on my NAS. Everything works fine when running v1.0.2.

I upgraded to the preview of v1.0.3 and restarted the master node. A short time later the node on my NAS was updated to v1.0.3. I tried to run a file through and got this error when it hits the MkvMerge script...

```
2022-09-07 20:57:49.209 [INFO] -> ======================================================================
2022-09-07 20:57:49.264 [ERRR] -> Execution error: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at FileFlows.FlowRunner.Runner.GetScriptCode(String scriptName) in /src/FlowRunner/Runner.cs:line 718
   at FileFlows.FlowRunner.Runner.LoadNode(FlowPart part) in /src/FlowRunner/Runner.cs:line 661
   at FileFlows.FlowRunner.Runner.ExecuteFlow(Flow flow, List`1 runFlows, Boolean failure) in /src/FlowRunner/Runner.cs:line 393
2022-09-07 20:57:49.267 [INFO] -> Node execution time: 00:00:00.0534368
```

I did not change anything in my configuration. So I reverted back to v1.0.2. I reset the master node to use the latest docker image tag and I reset the node on the NAS so it was running the same version as the master node. I tried the file again and it worked.

**Comment by revenz** [comment]
fixed
