### ISSUE TITLE
emby error

### ISSUE THREAD

**Issue by binarygeek119** [revenz/FileFlows#315]
`2022-09-08 01:44:31.522 [INFO] -> ======================================================================
2022-09-08 01:44:31.523 [INFO] -> Executing Node 13: EmbyUpdater [FileFlows.Emby.MediaManagement.EmbyUpdater]
2022-09-08 01:44:31.524 [INFO] -> ======================================================================
2022-09-08 01:44:31.602 [ERRR] -> Execution error: Object reference not set to an instance of an object.
   at FileFlows.Emby.MediaManagement.EmbyUpdater.Execute(NodeParameters args) in /src/Emby/MediaManagement/EmbyUpdater.cs:line 27
   at FileFlows.FlowRunner.Runner.ExecuteFlow(Flow flow, List'1 runFlows, Boolean failure) in /src/FlowRunner/Runner.cs:line 417
2022-09-08 01:44:31.604 [INFO] -> Node execution time: 00:00:00.0785568
2022-09-08 01:44:31.605 [INFO] -> ======================================================================`

**Comment by binarygeek119** [comment]
[FileFlows-Sep08-02.log](https://github.com/revenz/FileFlows/files/9524970/FileFlows-Sep08-02.log)
