### ISSUE TITLE
Cryptography error: Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by toverux** [revenz/FileFlows#357]
Hello,

I just setup my Server/Node on Ubuntu 22.10, following the wiki's instructions.
I get an error on any conversion job :

```
==============================================================================
===                      PROCESSING NODE OUTPUT START                      ===
==============================================================================
2022-11-01 17:38:28.246 [INFO] -> Error: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at FileFlows.FlowRunner.ConfigDecrypter.DecryptConfig(String file, String password) in /src/FlowRunner/ConfigDecrypter.cs:line 29
   at FileFlows.FlowRunner.Program.Main(String[] args) in /src/FlowRunner/Program.cs:line 51
2022-11-01 17:38:28.292 [INFO] -> Exit Code: 1
==============================================================================
===                       PROCESSING NODE OUTPUT END                       ===
==============================================================================
```

Let me know if you need more information.
 
Thanks,

**Comment by revenz** [comment]
can you post your nodes configuration file (if theres any passwords in there for gotify/email etc, send it via a DM on discord)

**Comment by toverux** [comment]
Hi, thank, and sure:

```
{
  "ServerUrl": "http://localhost:5000",
  "TempPath": "/home/morgan/FileFlows/Temp",
  "HostName": "saphir",
  "Runners": 0,
  "Enabled": true
}
```

Is that the file you were interested in?

(Btw, but unrelated: I noticed the Internal Processing Node, is it a default node coming with the server so I dont need to setup an actual separate node for localhost usage? Didn't find info about it in the wiki.)

**Comment by toverux** [comment]
Well I don't know what the file is so here's a dump of all .json and .config files of FileFlows: [configsfiles.zip](https://github.com/revenz/FileFlows/files/9933020/configsfiles.zip)

**Comment by revenz** [comment]
working on a similar (same) problem with a patreon member, once I hear back from them I'll do a new public release

**Comment by revenz** [comment]
is this still happening in 1.0.8?

**Comment by toverux** [comment]
I can confirm that it is working now. My first file is being processed! Thanks!
