### ISSUE TITLE
WatchedLibrary: An item with the same key has already been added

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#370]
```
Error -> Error: An item with the same key has already been added. Key: ee25131e-681d-48bb-acf7-65f33872cee8:/media/Movies
at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at FileFlows.Server.Workers.LibraryWorker.Watch(Library[] libraries) in /src/Server/Workers/LibraryWorker.cs:line 57
at FileFlows.Server.Workers.LibraryWorker.UpdateLibrariesInstance()
at FileFlows.Server.Workers.LibraryWorker.UpdateLibraries() in /src/Server/Workers/LibraryWorker.cs:line 50
at FileFlows.Server.Workers.LibraryWorker.Start() in /src/Server/Workers/LibraryWorker.cs:line 32
at FileFlows.Server.Workers.WorkerManager.StartWorkers(Worker[] workers) in /src/ServerShared/Workers/WorkerManager.cs:line 26
at FileFlows.Server.WebServer.Start(String[] args) in /src/Server/WebServer.cs:line 178
at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 114`
```

**Comment by revenz** [comment]
fixed
