### ISSUE TITLE
Function not implemented. Not able to start with docker

### ISSUE THREAD

**Issue by gk-fschubert** [revenz/FileFlows#428]
Hi, 

when I start the container, I get the following error:

```
2023-03-08 12:45:24.839 [INFO] -> Running inside docker container
2023-03-08 12:45:24.938 [INFO] -> ==================================================
2023-03-08 12:45:24.977 [INFO] -> Starting FileFlows 1.0.10.2222
2023-03-08 12:45:25.015 [DBUG] -> Arguments: --urls=http://*:5000 --docker
2023-03-08 12:45:25.052 [DBUG] -> ENV.S6_VERBOSITY = 1
2023-03-08 12:45:25.088 [DBUG] -> ENV.LD_LIBRARY_PATH = /usr/lib/x86_64-linux-gnu
2023-03-08 12:45:25.123 [DBUG] -> ENV.LIBVA_DRIVERS_PATH = /usr/lib/x86_64-linux-gnu/dri
2023-03-08 12:45:25.158 [DBUG] -> ENV.NVIDIA_DRIVER_CAPABILITIES = compute,video,utility
2023-03-08 12:45:25.193 [DBUG] -> ENV.OLDPWD = /app
Info -> Maximum concurrent database connections: 1
2023-03-08 12:45:25.233 [DBUG] -> ENV.LANGUAGE = en_US.UTF-8
2023-03-08 12:45:25.272 [DBUG] -> ENV.SHLVL = 0
Info -> Database initialized
2023-03-08 12:45:25.309 [DBUG] -> ENV.DOTNET_CLI_TELEMETRY_OPTOUT = true
2023-03-08 12:45:25.347 [DBUG] -> ENV.S6_STAGE2_HOOK = /docker-mods
2023-03-08 12:45:25.383 [DBUG] -> ENV.LANG = en_US.UTF-8
2023-03-08 12:45:25.422 [DBUG] -> ENV.TZ = Europe/Berlin
2023-03-08 12:45:25.456 [DBUG] -> ENV.S6_CMD_WAIT_FOR_SERVICES_MAXTIME = 0
2023-03-08 12:45:25.490 [DBUG] -> ENV.NVIDIA_VISIBLE_DEVICES = all
2023-03-08 12:45:25.523 [DBUG] -> ENV.HOME = /root
2023-03-08 12:45:25.558 [DBUG] -> ENV.HOSTNAME = b8bdcbde98c9
2023-03-08 12:45:25.595 [DBUG] -> ENV.DOTNET_ROOT = /dotnet
2023-03-08 12:45:25.630 [DBUG] -> ENV.PATH = /dotnet:/dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2023-03-08 12:45:25.664 [DBUG] -> ENV.TempPathHost = /Users/lineconnect/Movies/fileflows/temp
2023-03-08 12:45:25.699 [DBUG] -> ENV.TERM = xterm
2023-03-08 12:45:25.735 [INFO] -> ==================================================
2023-03-08 12:45:25.768 [DBUG] -> ENV.PWD = /app/Server
2023-03-08 12:45:25.804 [INFO] -> Maximum concurrent database connections: 1
2023-03-08 12:45:25.840 [INFO] -> Database initialized
Info -> Current version: 1.0.10.2222
Info -> Finished checking upgrade scripts
2023-03-08 12:45:27.132 [INFO] -> Current version: 1.0.10.2222
2023-03-08 12:45:27.170 [INFO] -> Finished checking upgrade scripts
Starting FileFlows Server...
Error -> Error: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at FileFlows.Server.WebServer.Start(String[] args) in /src/Server/WebServer.cs:line 43
   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 114
Error: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at FileFlows.Server.WebServer.Start(String[] args) in /src/Server/WebServer.cs:line 43
   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 114
```

used compose: 
```yaml
version: '3.7'
services:
  fileflows-server:
    image: revenz/fileflows
    container_name: fileflows-server
    platform: linux/amd64
    environment:
      - TZ=Europe/Berlin
      - TempPathHost=/Users/lineconnect/Movies/fileflows/temp
      # - FFNODE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/lineconnect/Movies/fileflows:/app/Data
      - /Users/lineconnect/Movies/fileflows/logs:/app/Logs
      - /Users/lineconnect/Movies/fileflows/temp:/temp
      - /Users/lineconnect/Movies/convert:/media
    ports:
      - 8000:5000
    restart: unless-stopped
```

I don't know where my issue could be.

**Comment by revenz** [comment]
quick google brings up this
https://github.com/docker/for-mac/issues/5328

you on a mac?

**Comment by gk-fschubert** [comment]
Haven't thought about it.. I've multiple applications where mac is able to translate everything. But yes, it's working on a linux device. 

Sorry for wasting your time and thanks for the hint!
