### ISSUE TITLE
Array Index Out of Bounds with Video File Node

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#43]
I do get an Array Index out of bounds error with [this](https://drive.google.com/uc?export=download&id=1pGsnknkoIDRPKrW-YPFS7U31J09PeM4N) file. 
Relevant section from log (see penultimate log message):
```
2022-04-25 10:09:03.3918 - INFO -> ======================================================================
2022-04-25 10:09:03.3925 - INFO -> Executing Node 1: Video File
2022-04-25 10:09:03.3929 - INFO -> ======================================================================
2022-04-25 10:09:03.3976 - INFO -> Making request[GET]: http://localhost:5000/api/tool/name/FFMpeg
2022-04-25 10:09:03.4576 - INFO -> Video Information:
[mpegts @ 0x55716f3bf800] start time for stream 1 is not set in estimate_timings_from_pts
[mpegts @ 0x55716f3bf800] stream 1 : no TS found at start of file, duration not set
[mpegts @ 0x55716f3bf800] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from '/mnt/tempNAS/media/hdr/HDR-Sample.ts':
  Duration: 00:01:12.24, start: 0.999989, bitrate: 52032 kb/s
  Program 1 
  Stream #0:0[0x101]: Video: hevc (Main 10) ([36][0][0][0] / 0x0024), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x102](und): Audio: aac ([15][0][0][0] / 0x000F), 0 channels
2022-04-25 10:09:03.4638 - INFO -> Video stream duration: 00:01:12.2400000
2022-04-25 10:09:03.4727 - ERRR -> Index was outside the bounds of the array.,    at FileFlows.VideoNodes.VideoInfoHelper.ParseAudioStream(String info) in C:\BuildAgent\work\FileFlowsPlugins\VideoNodes\VideoInfoHelper.cs:line 238
   at FileFlows.VideoNodes.VideoInfoHelper.ParseOutput(ILogger logger, String output) in C:\BuildAgent\work\FileFlowsPlugins\VideoNodes\VideoInfoHelper.cs:line 113
   at FileFlows.VideoNodes.VideoInfoHelper.Read(String filename) in C:\BuildAgent\work\FileFlowsPlugins\VideoNodes\VideoInfoHelper.cs:line 67
2022-04-25 10:09:03.4734 - INFO -> No video streams detected.
```

**Comment by revenz** [comment]
Fixed in next version, just had to set a probesize, now defaults to 25M but can be overridden if needed.   25M works fine on the sample file provided.
