### ISSUE TITLE
Hardware encode but not decode?

### ISSUE THREAD

**Issue by famewolf** [revenz/FileFlows#448]
I have an i7-4790 currently being used in unmanic and it apparently has h264 hardware encoding but not decoding....I got vaapi to work in unmanic via a custom ffmpeg command line and adding an environment variable to add LIBVA_DRIVER_NAME=i965.

When using fileflows even though I specified to use hardware encode and not hardware decode it's not seeing it as available:

`2023-04-06 15:57:06.673 [INFO] -> Node execution time: 00:00:00.4026484
2023-04-06 15:57:06.673 [INFO] -> ======================================================================
2023-04-06 15:57:06.676 [INFO] -> ======================================================================
2023-04-06 15:57:06.676 [INFO] -> Executing Node 6: Video Encode [FileFlows.VideoNodes.FfmpegBuilderNodes.FfmpegBuilderVideoEncode]
2023-04-06 15:57:06.676 [INFO] -> ======================================================================
2023-04-06 15:57:06.714 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_nvenc -f null -': [h264_nvenc @ 0x55f83c448c80] Cannot load libcuda.so.1
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-06 15:57:06.744 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_qsv -f null -': [h264_qsv @ 0x5621ce681c80] Failed to create a VAAPI device.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-06 15:57:06.779 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_amf -f null -': [h264_amf @ 0x563ed41cbc80] DLL libamfrt64.so.1 failed to open
double free or corruption (fasttop)
2023-04-06 15:57:06.797 [WARN] -> Cant process '/usr/local/bin/ffmpeg -fflags +genpts -vaapi_device /dev/dri/renderD128 -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_vaapi -vf 'format=nv12,hwupload' -strict -2 /temp/Runner-5835e6ea-3ea9-426d-9919-4467f42678b4/359d2489-af9e-4338-b2d7-673133eedf83.mkv': [AVHWDeviceContext @ 0x563ebb7b0a80] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument`

**Comment by revenz** [comment]
have you followed the guide for it on docs.fileflows.com ?

According to this your CPU supports AVC (h264) encoding/decoding
https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video

**Comment by famewolf** [comment]
Yes and no.  I'm on Truenas scale which uses kubernetes and am using a prepackaged app from Truecharts.  However they have it set up it's not working with vaapi or quicksync even though the dri device is being passed in.  "[AVHWDeviceContext @ 0x563ebb7b0a80] No VA display found for device /dev/dri/renderD128. Device creation failed: -22. Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument Error parsing global options: Invalid argument"

**Comment by revenz** [comment]
closing.   if youre not using the official docker images/built images.   ask whoever created the docker image you are using

**Comment by famewolf** [comment]
I read this in another thread...I'm specifying to use the i965 driver in env variables..this should be calling vaapi...not trying to call the ihd driver.

"The ffmpeg qsv plugin depends on MediaSDK. MediaSDK does not support i965 driver. https://github.com/Intel-Media-SDK/MediaSDK#system-requirements.

You will need to use the ffmpeg vaapi plugin with the i965 driver, instead."

Taken from log:  [AVHWDeviceContext @ 0x56216c976a00] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed

Fine, close it...I'll go back to unmanic that calls the correct driver.

**Comment by revenz** [comment]
I have no idea what version of ffmpeg that docker container is using. No idea what else is in that docker container. I cannot supoort because of those 

If you can make it work using a function command and working out the parameters that works then I can update.  But it could be just the ffmpeg build in question

**Comment by famewolf** [comment]
I have manually configured YOUR docker container (which truecharts WAS calling via a helm chart but they were running as a user and not as root so to ignore potential issues I setup the docker manually) and am getting identical results with my i7-4790 cpu which should be using VAAPI and the i965  driver.  Instead the iHD driver is being called.    I passed in LIBVA_DRIVER_NAME=i965 in an environment variable (which is what worked in unmanic) however your container appears to ignore it.

2023-04-09 17:24:32.798 [INFO] -> ======================================================================
2023-04-09 17:24:32.798 [INFO] -> Executing Node 6: Video Encode [FileFlows.VideoNodes.FfmpegBuilderNodes.FfmpegBuilderVideoEncode]
2023-04-09 17:24:32.798 [INFO] -> ======================================================================
2023-04-09 17:24:32.832 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_nvenc -f null -': [h264_nvenc @ 0x557ff483bc80] Cannot load libcuda.so.1
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-09 17:24:32.883 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_qsv -f null -': [AVHWDeviceContext @ 0x5564c59e0a00] **libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed**
[AVHWDeviceContext @ 0x5564c59e0a00] Failed to initialise VAAPI connection: 1 (operation failed).
[h264_qsv @ 0x5564c58a3c80] Failed to create a VAAPI device.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-09 17:24:32.912 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_amf -f null -': [h264_amf @ 0x56051a51ec80] DLL libamfrt64.so.1 failed to open
double free or corruption (fasttop)
2023-04-09 17:24:32.947 [WARN] -> Cant process '/usr/local/bin/ffmpeg -fflags +genpts -vaapi_device /dev/dri/renderD128 -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_vaapi -vf 'format=nv12,hwupload' -strict -2 /temp/Runner-305d0db9-3bc6-4546-8c70-991e8480db08/6271f73f-d7c0-4b76-b4b3-f619f98a3a1f.mkv': [AVFilterGraph @ 0x557a8d2fc980] No such filter: 'format=nv12,hwupload'
Error reinitializing filters!

So tell me what else you want to see.

**Comment by revenz** [comment]
Since no other users are reporting this issue, and my only intel CPU with QSV works.   This is what I'm going to need

1. Create a function that calls FFmpeg manually
2. Work out the exact parameters needed to check FFmpeg is able to use that hardware decoder
3. Work out the exact parameters needed to then use that hardware decoder 

I can then update the code to reflect this

**Comment by revenz** [comment]
can you provide an updated test as well that passes for you.  need to know the runner can use hardware encoding before use it

**Comment by famewolf** [comment]
I just did provide one that passes for me using vaapi?  I had to remove -hwaccel_device from beginning or it tells you:
Option hwaccel_device (select a device for HW acceleration) cannot be applied to output url ffmpeg -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file ffmpeg.
Error opening output files: Invalid argument

Test file used was:  https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4

**Comment by revenz** [comment]
the test doesnt have access to a video file.   these are the tests it currently runs
```
2023-04-09 17:24:32.832 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_nvenc -f null -': [h264_nvenc @ 0x557ff483bc80] Cannot load libcuda.so.1
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-09 17:24:32.883 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_qsv -f null -': [AVHWDeviceContext @ 0x5564c59e0a00] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x5564c59e0a00] Failed to initialise VAAPI connection: 1 (operation failed).
[h264_qsv @ 0x5564c58a3c80] Failed to create a VAAPI device.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-04-09 17:24:32.912 [WARN] -> Cant process '/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_amf -f null -': [h264_amf @ 0x56051a51ec80] DLL libamfrt64.so.1 failed to open
double free or corruption (fasttop)
2023-04-09 17:24:32.947 [WARN] -> Cant process '/usr/local/bin/ffmpeg -fflags +genpts -vaapi_device /dev/dri/renderD128 -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_vaapi -vf 'format=nv12,hwupload' -strict -2 /temp/Runner-305d0db9-3bc6-4546-8c70-991e8480db08/6271f73f-d7c0-4b76-b4b3-f619f98a3a1f.mkv': [AVFilterGraph @ 0x557a8d2fc980] No such filter: 'format=nv12,hwupload'
```

**Comment by famewolf** [comment]
As far as I know they all still fail...probably because it's calling the iHD driver instead of the i965.  I'll run them manually:

/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_nvenc -f null -
[h264_nvenc @ 0x55aed04f5c80] Cannot load libcuda.so.1
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

# /usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_qsv -f null -
[AVHWDeviceContext @ 0x56342b62c9c0] libva: /usr/lib/x86_64-linux-gnu/dri/**iHD_drv_video.so** init failed
[AVHWDeviceContext @ 0x56342b62c9c0] Failed to initialise VAAPI connection: 1 (operation failed).
[h264_qsv @ 0x56342b4efc80] Failed to create a VAAPI device.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
# 
/usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_amf -f null -
[h264_amf @ 0x55b1153e0c80] DLL libamfrt64.so.1 failed to open
double free or corruption (fasttop)
Aborted [It kicked me out of the shell into the container at this point]

**Comment by famewolf** [comment]
Perhaps if all 3 fail but /dev/dri/renderD128 exists it can then fallback to vaapi?

**Comment by revenz** [comment]
yeah, thats what I  need first.  step one is detect the runner can use hardware, so it does those checks, taht check is failing on your setup, so I need help figuring out a new test to detect it.  it falls back to CPU if no hardware encoders can be used so the run can proceed.

**Comment by famewolf** [comment]
Not sure if I can change this to work:
# /usr/local/bin/ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_vaapi -f null -
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
#

**Comment by famewolf** [comment]
If all else fails perhaps you could let the user select vaapi in the config for the transcode video module?

**Comment by famewolf** [comment]
If all else fails perhaps you could let the user select vaapi in the config for the transcode video module?  Or perhaps the user could enable via an environment variable passed into the container?

**Comment by famewolf** [comment]
In my particular case,  is there a way I could use "custom parameters" to enable vaapi?   Specifically these:   -vaapi_device /dev/dri/renderD128  -vf format=nv12,hwupload -c:v h264_vaapi         The biggest problem I'm going to guess is I can't specifically set the h264_vaapi driver?

**Comment by revenz** [comment]
if youre going to that level of custom ffmpeg, just use the Video Codec node instead and set those as the paraemeters

**Comment by revenz** [comment]
fully  custom with an Function and executing ffmpeg manually?

**Comment by revenz** [comment]
The [Function node](https://docs.fileflows.com/plugins/basic-nodes/function) is the most powerful node in the system.

It has some templates built in, one of those templates is a custom FFmpeg command.

**Comment by famewolf** [comment]
Ran into this while working on the flow:

Module._mono_wasm_invoke_method@http://192.168.3.117:10242/_framework/dotnet.6.0.11.b4vqcojopb.js:1:219002
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS@https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16:40
endInvokeJSFromDotNet@http://192.168.3.117:10242/_framework/blazor.webassembly.js:1:42115
beginInvokeJSFromDotNet/<@http://192.168.3.117:10242/_framework/blazor.webassembly.js:1:3371

   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by famewolf** [comment]
Not sure if it helps or hurts to point out my machine DOES pass your hardware DECODING test.  
2023-04-13 14:37:06.561 [INFO] -> Executing: /usr/local/bin/ffmpeg -y -hwaccel vaapi -hwaccel_output_format vaapi -f lavfi -i color=color=red -frames:v 10 /temp/Runner-8c8dac21-a920-4436-ad5d-383139a16363/bef25f3b-abc3-45ab-a202-b89b751cf741.hwtest.mkv
2023-04-13 14:37:06.561 [INFO] -> ----------------------------------------------------------------------
2023-04-13 14:37:06.576 [INFO] -> ffmpeg version 5.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
2023-04-13 14:37:06.576 [INFO] ->   built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
2023-04-13 14:37:06.577 [INFO] ->   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
2023-04-13 14:37:06.577 [INFO] ->   libavutil      57. 28.100 / 57. 28.100
2023-04-13 14:37:06.577 [INFO] ->   libavcodec     59. 37.100 / 59. 37.100
2023-04-13 14:37:06.577 [INFO] ->   libavformat    59. 27.100 / 59. 27.100
2023-04-13 14:37:06.577 [INFO] ->   libavdevice    59.  7.100 / 59.  7.100
2023-04-13 14:37:06.577 [INFO] ->   libavfilter     8. 44.100 /  8. 44.100
2023-04-13 14:37:06.577 [INFO] ->   libswscale      6.  7.100 /  6.  7.100
2023-04-13 14:37:06.577 [INFO] ->   libswresample   4.  7.100 /  4.  7.100
2023-04-13 14:37:06.577 [INFO] ->   libpostproc    56.  6.100 / 56.  6.100
2023-04-13 14:37:06.577 [INFO] -> Input #0, lavfi, from 'color=color=red':
2023-04-13 14:37:06.577 [INFO] ->   Duration: N/A, start: 0.000000, bitrate: N/A
2023-04-13 14:37:06.577 [INFO] ->   Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn
2023-04-13 14:37:06.578 [INFO] -> Stream mapping:
2023-04-13 14:37:06.578 [INFO] ->   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
2023-04-13 14:37:06.578 [INFO] -> Press [q] to stop, [?] for help
2023-04-13 14:37:06.583 [INFO] -> [libx264 @ 0x562ada803300] using SAR=1/1
2023-04-13 14:37:06.584 [INFO] -> [libx264 @ 0x562ada803300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
2023-04-13 14:37:06.585 [INFO] -> [libx264 @ 0x562ada803300] profile High, level 1.3, 4:2:0, 8-bit
2023-04-13 14:37:06.585 [INFO] -> [libx264 @ 0x562ada803300] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
2023-04-13 14:37:06.585 [INFO] -> Output #0, matroska, to '/temp/Runner-8c8dac21-a920-4436-ad5d-383139a16363/bef25f3b-abc3-45ab-a202-b89b751cf741.hwtest.mkv':
2023-04-13 14:37:06.585 [INFO] ->   Metadata:
2023-04-13 14:37:06.585 [INFO] ->     encoder         : Lavf59.27.100
2023-04-13 14:37:06.585 [INFO] ->   Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 25 fps, 1k tbn
2023-04-13 14:37:06.585 [INFO] ->     Metadata:
2023-04-13 14:37:06.585 [INFO] ->       encoder         : Lavc59.37.100 libx264
2023-04-13 14:37:06.585 [INFO] ->     Side data:
2023-04-13 14:37:06.585 [INFO] ->       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
2023-04-13 14:37:06.585 [INFO] -> frame=    1 fps=0.0 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
2023-04-13 14:37:06.592 [INFO] -> frame=   10 fps=0.0 q=-1.0 Lsize=       2kB time=00:00:00.28 bitrate=  44.9kbits/s speed=21.5x    
2023-04-13 14:37:06.592 [INFO] -> video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 74.364639%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] frame I:1     Avg QP:10.00  size:    69
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] frame P:3     Avg QP:11.67  size:    20
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] frame B:6     Avg QP:12.67  size:    14
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] consecutive B-frames: 20.0%  0.0%  0.0% 80.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] mb I  I16..4: 100.0%  0.0%  0.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:100.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.0%  0.0%  0.0%  direct: 0.0%  skip:100.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] 8x8 transform intra:0.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] coded y,uvDC,uvAC intra: 0.0% 0.3% 0.0% inter: 0.0% 0.0% 0.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] i16 v,h,dc,p: 93%  0%  7%  0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] i8c dc,h,v,p: 100%  0%  0%  0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] Weighted P-Frames: Y:0.0% UV:0.0%
2023-04-13 14:37:06.609 [INFO] -> [libx264 @ 0x562ada803300] kb/s:4.32
2023-04-13 14:37:06.612 [INFO] -> Supported hardware decoding detected: -hwaccel vaapi -hwaccel_output_format vaapi
2023-04-13 14:37:06.612 [INFO] -> ### Total Time: 00:41:39.1300000

**Comment by revenz** [comment]
Closing, this issue got out of hand and all over the place.

Created #485 which should cover what is needed I believe for this.
