### ISSUE TITLE
Error while loading dashboard 

### ISSUE THREAD

**Issue by danylkaaa** [revenz/FileFlows#458]
- Version: 1.1.0.2263
- Docker
- Unraid

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found (Parameter 'resourceKey')
System.ArgumentException: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found (Parameter 'resourceKey')
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords)
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForDate(TimeUnit unit, Tense timeUnitTense, Int32 count)
   at Humanizer.Localisation.Formatters.DefaultFormatter.DateHumanize(TimeUnit timeUnit, Tense timeUnitTense, Int32 unit)
   at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize(TimeSpan ts, Boolean sameMonth, Int32 days, Tense tense, CultureInfo culture)
   at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
   at Humanizer.DateTimeHumanizeStrategy.DefaultDateTimeHumanizeStrategy.Humanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
   at Humanizer.DateHumanizeExtensions.Humanize(DateTime input, Nullable`1 utcDate, Nullable`1 dateToCompareAgainst, CultureInfo culture)
   at FileFlows.Client.Pages.ListPage`2[[System.Guid, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FileFlows.Shared.Models.LibaryFileListModel, FileFlows.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].DateString(Nullable`1 date)
   at FileFlows.Client.Pages.LibraryFiles.<>c__DisplayClass61_2.<BuildRenderTree>b__27(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at FileFlows.Client.Components.Common.FlowTable`1.<>c__DisplayClass122_0[[FileFlows.Shared.Models.LibaryFileListModel, FileFlows.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__9(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1[[System.Collections.Generic.KeyValuePair`2[[FileFlows.Shared.Models.LibaryFileListModel, FileFlows.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
w
```

Console:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/17959494/232723051-8fd0d9ae-5390-49fb-9ff5-5a1b114eb802.png">

**Comment by danylkaaa** [comment]
Hi, @revenz can I do smth to help you debug and fix this?

**Comment by revenz** [comment]
might be fixed in next version.   ive upgraded fileflows to .net 7 and all nuget packages for that version

**Comment by danylkaaa** [comment]
@revenz more details: error appear when browser uses non-english by default. Tested in 2 Chrome instances with different locales config. Looks like the root of the issue, is that DateHumanize tries to use date format, used in my locale, but cannot found it and crashes

**Comment by revenz** [comment]
Cannot repo this.  Tried several different languages.   Both chrome and firefox.

But I have tried to put in a fix for it.  So when 23.06.2 (or greater) comes out, let me know if its fixed.

![Image](https://github.com/revenz/FileFlows/assets/958400/c064663f-a280-43ea-93f4-80bc027d34f5)
