### ISSUE TITLE
File Flows not running on raspberry pi

### ISSUE THREAD

**Issue by walksanatora** [revenz/FileFlows#59]
hello i installed dotnet
and when i use it it crashes stating 
```
2022-05-07 21:26:00.1960 - ERRR -> Error: Could not load file or assembly 'FileFlows.Node, Version=0.5.4.756, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at FileFlows.Server.WebServer.Start(String[] args)
   at FileFlows.Server.Program.Main(String[] args) in C:\BuildAgent\work\FileFlows\Server\Program.cs:line 24
Error in Logger: Could not find a part of the path '/app/Logs/FileFlows.log'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.AppendAllText(String path, String contents)
   at FileFlows.Server.Logger.Log(LogType type, Object[] args) in C:\BuildAgent\work\FileFlows\Server\Logger.cs:line 94
Error: Could not load file or assembly 'FileFlows.Node, Version=0.5.4.756, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at FileFlows.Server.WebServer.Start(String[] args)
   at FileFlows.Server.Program.Main(String[] args) in C:\BuildAgent\work\FileFlows\Server\Program.cs:line 24
   ```

**Comment by revenz** [comment]
fixed in 0.6.0
